AppCoinStash/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'coinsearch', views.CoinSearchViewSet, basename='coinsearch')

app_name = 'AppCoinStash'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('<str:coin_ticker>/detail', views.detail, name='detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.RegisterView.as_view(), name="register"),
    path('', include(router.urls)),
    path('add_coin', views.add_coin, name='add_coin'),
    path('del_coin', views.del_coin, name='del_coin'),
    path('add_transaction', views.add_transaction, name='add_transaction'),
    path('del_transaction', views.del_transaction, name='del_transaction'),
    path('chart_data', views.get_chart_data, name='chart_data'),
]

ProjCryptoCurrency/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('AppCoinStash.urls')),
    path('admin/', admin.site.urls),
]

AppCoinStash/models.py
from decimal import Decimal

from django.db import models
from django.contrib.auth import get_user_model

# TODO: React with Parallax frontend
# TODO: Add password reset (Gmail SMTP) and change password
# TODO: Add server-side input validation


class Coin(models.Model):
    COINGECKO = 1
    COINMARKETCAP = 2
    API_TYPE = [
        (COINGECKO, "COINGECKO"),
        (COINMARKETCAP, "COINMARKETCAP"),
    ]

    coin_api_id = models.CharField(max_length=200)
    coin_ticker = models.CharField(max_length=200)
    coin_name = models.CharField(max_length=200)
    coin_api_type = models.PositiveSmallIntegerField(
        choices=API_TYPE,
        default=COINGECKO
    )

    current_price = Decimal(0)
    gain_loss = Decimal(0)
    avg_cost = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    total_cost = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    balance = models.DecimalField(max_digits=30, decimal_places=18, default=0.0)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.coin_name

    # Must save after calling this function
    def reset_metrics(self):
        self.avg_cost = Decimal(0)
        self.total_cost = Decimal(0)
        self.balance = Decimal(0)

    # Must save after calling this function
    def update_avg_cost(self):
        if self.balance <= 0 or self.total_cost <= 0:  # exited the market
            self.avg_cost = 0
            self.total_cost = 0
        else:
            self.avg_cost = self.total_cost / self.balance

    # Parse a single transaction
    def parse_transaction(self, transaction):
        if transaction.transaction_type == 1:
            self.total_cost += transaction.sent_qty
            self.balance += transaction.received_qty
        else:
            self.total_cost -= self.avg_cost * transaction.sent_qty
            self.balance -= transaction.sent_qty

        self.update_avg_cost()
        transaction.parsed = True
        transaction.save()
        self.save()

    # Parse all transactions
    def reparse_transaction_history(self):
        transactions = Transaction.objects.filter(coin=self).order_by('transaction_date')
        self.reset_metrics()
        self.save()
        for transaction in transactions:
            self.parse_transaction(transaction=transaction)


class Transaction(models.Model):
    """
    Fiat/Coin and Coin/Fiat are the only supported transactions.
    Coin/Coin transactions are not. This enables inference of
    currency of sent and received quantities.
    """
    coin = models.ForeignKey(Coin, on_delete=models.CASCADE)

    BUY = 1
    SELL = 2
    TRANSACTION_TYPE = [
        (BUY, "BUY"),
        (SELL, "SELL"),
    ]

    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE,
        default=BUY
    )
    transaction_date = models.DateTimeField()
    received_qty = models.DecimalField(max_digits=30, decimal_places=18)
    sent_qty = models.DecimalField(max_digits=30, decimal_places=18)
    parsed = models.BooleanField()


class CoinList(models.Model):
    coin_id = models.CharField(max_length=200)
    coin_symbol = models.CharField(max_length=200)
    coin_name = models.CharField(max_length=200)

    def __str__(self):
        return self.coin_name

AppCoinStash/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.dateparse import parse_datetime
from django.views import generic
from rest_framework import viewsets

from decimal import Decimal
from . import coin_api
from .models import Coin, CoinList, Transaction
from .serializers import CoinListSerializer


def index(request):
    return render(request, 'index.html')


class HomeView(LoginRequiredMixin, generic.ListView):
    model = Coin
    template_name = 'home.html'

    def get_queryset(self):
        coins = Coin.objects.filter(user=self.request.user).order_by('-total_cost')
        coin_api.fetch_prices(coins)
        return coins


@login_required
def detail(request, coin_ticker):
    coin = get_object_or_404(Coin, coin_ticker=coin_ticker, user=request.user)
    recent_transactions = coin.transaction_set.filter(parsed=True).order_by('-transaction_date')[:10]
    image_url = None

    return render(request, 'detail.html', {
        'coin': coin,
        'transactions': recent_transactions,
        'image_url': image_url,
    })


# https://docs.djangoproject.com/en/4.0/topics/class-based-views/generic-editing/
class RegisterView(SuccessMessageMixin, generic.edit.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('AppCoinStash:home')
    template_name = 'registration/register.html'
    success_message = "Registered successfully!"


class CoinSearchViewSet(viewsets.ModelViewSet):
    serializer_class = CoinListSerializer

    def get_queryset(self):
        search_string = self.request.query_params.get('search_string')
        queryset = CoinList.objects.filter(
            Q(coin_symbol__iexact=search_string) | Q(coin_name__istartswith=search_string))\
            .order_by('coin_name')
        return queryset[:10]


@login_required
def add_coin(request):
    coin_id = request.POST.get('new_coin')
    coin_data = CoinList.objects.filter(coin_id=coin_id)
    if not coin_data:
        messages.error(request, 'The coin is currently not supported.')
    else:
        cdata = coin_data[0]
        if Coin.objects.filter(user=request.user, coin_ticker=cdata.coin_symbol).exists():
            messages.error(request, 'The coin is already in your portfolio.')
        else:
            new_coin = Coin(user=request.user,
                            coin_ticker=cdata.coin_symbol,
                            coin_name=cdata.coin_name,
                            coin_api_id=cdata.coin_id)
            new_coin.save()
            messages.success(request, 'Coin added successfully.')
    return redirect('home/')


@login_required
def add_transaction(request):
    coin = Coin.objects.get(user=request.user, coin_ticker=request.POST.get('coin_ticker'))
    if coin:
        trans_type = int(request.POST.get('trans_type'))
        datetime = parse_datetime(request.POST.get('datetime'))
        sent_qty = Decimal(request.POST.get('sent_qty'))
        recv_qty = Decimal(request.POST.get('recv_qty'))
        transaction = Transaction(coin=coin,
                                  transaction_type=trans_type,
                                  transaction_date=datetime,
                                  received_qty=recv_qty,
                                  sent_qty=sent_qty,
                                  parsed=False)
        transaction.save()
        coin.parse_transaction(transaction=transaction)
        messages.success(request, 'Added transaction successfully.')
    else:
        messages.error(request, 'Coin not found.')

    return redirect('AppCoinStash:detail', coin_ticker=request.POST.get('coin_ticker'))


@login_required
def del_transaction(request):
    transaction = Transaction.objects.get(id=request.POST.get('tx_id'))
    coin = Coin.objects.get(coin_ticker=request.POST.get('coin_ticker'))
    if transaction and coin:
        transaction.delete()
        coin.reparse_transaction_history()
    else:
        messages.error(request, 'Could not delete transaction.')

    return redirect('AppCoinStash:detail', coin_ticker=request.POST.get('coin_ticker'))


@login_required
def del_coin(request):
    coin = Coin.objects.get(user=request.user, coin_ticker=request.POST.get('coin_ticker'))
    if coin:
        coin.delete()
        messages.warning(request, request.POST.get('coin_ticker').capitalize() + ' removed from portfolio.')
    else:
        messages.error(request, 'Could not remove coin.')
    return redirect('AppCoinStash:home')
    pass


@login_required
def get_chart_data(request):
    coins = Coin.objects.filter(user=request.user).order_by('-total_cost')
    rsp = {}
    for coin in coins:
        if coin.total_cost > 0:
            rsp.__setitem__(coin.coin_ticker.upper(), coin.total_cost)
    return JsonResponse(rsp)

AppCoinStash/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'AppCoinStash/style.css' %}">
    {% block page_specific_style %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <title>{% block title %}Base HTML{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand" href="/"><img alt="logo" src="{% static 'AppCoinStash/images/logo_512px.png' %}"  width="30px">&nbsp;&nbsp;<span>CoinStash</span></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item custom-nav-item">
                        <a class="nav-link btn btn-primary-outline" href="{% url 'AppCoinStash:register' %}">
                            <span>Register</span>
                        </a>
                    </li>
                    <li class="nav-item custom-nav-item">
                        <a class="nav-link" href="{% url 'AppCoinStash:login' %}">
                            <span>Login</span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'AppCoinStash:home' %}">
                            <span>Welcome, {{ user.username }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'AppCoinStash:home' %}">
                            <span>Portfolio</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'AppCoinStash:logout' %}">
                            <span>Logout</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<div class="container-fluid p-0">
    {% block content-fluid %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

AppCoinStash/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block page_specific_style %}
    <style>
        #del_coin_button {
            position: absolute;
            right: 16em;
            bottom: 0;
            border-radius: 25px;
            color: white;
            background-color: #dc3545;
        }
        #del_coin_button:hover {
            background-color: #c82333;
        }
        #csv_button {
            position: absolute;
            right: 9em;
            bottom: 0;
            border-radius: 25px;
        }
        #new_transaction_button {
            position: absolute;
            right: 0;
            bottom: 0;
            border-radius: 25px;
        }
        #new_transaction_button:hover {
            background-color: #cccccc;
        }
        .delete_trans_button {
            border-radius: 25px;
        }
        .delete_trans_button:hover {
            background-color: #cccccc;
        }
        #new_transaction_form {
            position: absolute;
            right: 0;
            border: 1px solid grey;
            padding: 1em;
            margin-top: 1em;
            background-color: whitesmoke;
            border-radius: 5px;
        }
        #submit_form_button {
            border-bottom: 2px solid black;
        }
        #cancel_form_button {
            position: absolute;
            right: 1em;
            border-bottom: 2px solid black;
        }
        ul.messages {
            padding: 0;
            list-style-type: none;
        }
        .buy_row {
            color: green;
            font-weight: bold;
        }
        .sell_row {
            color: red;
            font-weight: bold;
        }
        #transaction_table tbody tr:hover {
            background-color: lightgrey;
        }
    </style>
{% endblock %}

{% block title %}{{ user.username }} - {{ coin.coin_name }}{% endblock %}

{% block content %}
    {% if messages %}
        <ul class="messages" style="list-style-type:none;">
            {% for message in messages %}
                <li{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row mt-5 mb-1">
        <h3 style="text-decoration: underline;">{{ coin.coin_name }}</h3>
    </div>
    <div class="row">
        <table class="table table-striped">
            <tr>
                <td class="py-1">Average Cost</td>
                <td class="py-1 text-right">${{ coin.avg_cost }} CAD</td>
            </tr>
            <tr>
                <td class="py-1">Total Cost</td>
                <td class="py-1 text-right">${{ coin.total_cost }} CAD</td>
            </tr>
            <tr>
                <td class="py-1">Balance</td>
                <td class="py-1 text-right">{{ coin.balance|floatformat:5 }} {{ coin.coin_ticker.upper }}</td>
            </tr>
        </table>
    </div>
    <div class="row mt-5">
        <div class="col pl-0">
            <h3 style="text-decoration: underline">Transactions</h3>
        </div>
        <div class="col">
            <button id="new_transaction_button" class="px-2" onclick="show_form()">New transaction</button>
            <button id="csv_button" class="px-2" disabled>Upload CSV</button>
            <form id="del_form" method="post" action="{% url 'AppCoinStash:del_coin' %}" hidden>
                {% csrf_token %}
                <input type="text" name="coin_ticker" value="{{ coin.coin_ticker }}" hidden/>
            </form>
            <button form="del_form" type="submit" id="del_coin_button" class="px-2">Remove coin</button>
        </div>
    </div>
    <div class="row">
        <div class="col" style="background-color: whitesmoke;">
            <form id="new_transaction_form" method="post" action="{% url 'AppCoinStash:add_transaction' %}" hidden>
                {% csrf_token %}
                <h5>Add new transaction</h5>
                <input type="text" name="coin_ticker" value="{{ coin.coin_ticker }}" hidden/>
                <table id="new_form_table" class="table table-striped">
                    <tr>
                        <td class="text-right"><label for="datetime">Date:&nbsp;</label></td>
                        <td><input type="datetime-local" id="datetime" name="datetime" required></td>
                    </tr>
                    <tr>
                        <td class="text-right"><label for="trans_type">Transaction type:&nbsp;</label></td>
                        <td>
                            <select id="trans_type" name="trans_type" required>
                                <option value=1>BUY</option>
                                <option value=2>SELL</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right"><label for="sent_qty">Sent quantity:&nbsp;</label></td>
                        <td><input type=number id="sent_qty" name="sent_qty" min="0" step=any required/></td>
                    </tr>
                    <tr>
                        <td class="text-right"><label for="recv_qty">Received quantity:&nbsp;</label></td>
                        <td><input type=number id="recv_qty" name="recv_qty" min="0" step=any required/></td>
                    </tr>
                </table>
                <input id="submit_form_button" type="submit" class="btn btn-primary" value="Submit">
                <button id="cancel_form_button" class="btn btn-secondary" onclick="hide_form()">Close</button>
            </form>
        </div>
    </div>
    {% if transactions %}
        <div class="row">
            <table id="transaction_table" class="table table-striped mt-2">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Sent</th>
                    <th>Received</th>
                    <th></th>
                </tr>
                </thead>
                {% for tx in transactions %}
                    <tr class="{% if tx.transaction_type == 1 %}buy_row{% else %}sell_row{% endif %}">
                        <td class="py-1">{{ tx.transaction_date }}</td>
                        <td class="py-1">{{ tx.sent_qty|floatformat:2|intcomma }}</td>
                        <td class="py-1">{{ tx.received_qty|floatformat:2|intcomma }}</td>
                        <td class="py-1 text-right">
                            <form id="del{{ tx.id }}" method="post" action="{% url 'AppCoinStash:del_transaction' %}" hidden>
                                {% csrf_token %}
                                <input type="number" name="tx_id" value="{{ tx.id }}">
                                <input type="text" name="coin_ticker" value="{{ coin.coin_ticker }}">
                            </form>
                            <button form="del{{ tx.id }}" class="delete_trans_button pa-1" type="submit">Delete</button>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <p class="text-center">No transactions yet.</p>
    {% endif %}
    <script>
        function show_form() {
            set_max_date()
            $('#new_transaction_form').removeAttr('hidden')
        }
        function hide_form() {
            $('#datetime').val('')
            $('#sent_qty').val('')
            $('#recv_qty').val('')
            $('#new_transaction_form').attr('hidden', '')
        }
        function set_max_date() {
            $('#datetime').attr('max', new Date().toISOString().split(".")[0])
        }
    </script>
{% endblock %}

AppCoinStash/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block page_specific_style %}
    <style>
        #result {
            border: 1px solid #ccc;
            padding: 3px;
            z-index: 2;
            border-radius: 5px;
        }
        #result ol {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        #result ol li {
            padding-top: 5px;
            padding-left: 10px;
            padding-bottom: 5px;
        }
        #result ol li:not(:last-child) {
            border-bottom: 1px solid lightgrey;
        }
        #result ol li:hover {
            background: lightgrey;
        }
        #submit_coin {
            margin-left: 5px;
        }
        ul.messages{
            padding: 0;
            list-style-type: none;
        }
        button {
            border-radius: 20px;
        }
        input {
            border-radius: 10px;
            background-color: whitesmoke;
        }
        input:focus {
            background-color: seashell;
        }
        .chart-container {
            text-align: center;
            max-width: 300px;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
{% endblock %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if messages %}
        <ul class="messages" style="list-style-type:none;">
            {% for message in messages %}
                <li{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row" style="margin-top: 10px;">
        <div class="col text-right">
            <form autocomplete="off" method="post" action="http://127.0.0.1:8000/add_coin">
                {% csrf_token %}
                <div class="form-group">
                    <label for="new_coin">Search:</label>
                    <input placeholder="btc, dogecoin, ..." name="new_coin" id="new_coin" oninput="searchCoinList(this.value)" onfocusout="clearSearch()" />
                    <button id="submit_coin" type="submit" disabled>Add to portfolio</button>
                    <div id="result" style="background-color: whitesmoke; position: absolute; text-align: left; width: 40%; right: 0;" hidden></div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <h3 style="text-decoration: underline;">Portfolio</h3>
    </div>
    {% if coin_list %}
        <div id="homechart_div" class="chart-container" hidden>
            <canvas id="homeChart"></canvas>
        </div>
        <div class="row">
            {% for coin in coin_list %}
                <div class="col-4 my-4">
                    <div class="card w-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ coin.coin_ticker.upper }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ coin.coin_name }} - ${{ coin.current_price|floatformat:2|intcomma }} CAD</h6>
                            <h3 class="{% if coin.gain_loss >= 0 %}green-text{% else %}red-text{% endif %}" style="position: absolute; right: .7em; top: 0.5em;">{{ coin.gain_loss|floatformat:2 }}%</h3>
                            <table class="table table-striped">
                                <tr>
                                    <td class="py-1">Average Cost</td>
                                    <td class="py-1 text-right">${{ coin.avg_cost|floatformat:2|intcomma }} CAD</td>
                                </tr>
                                <tr>
                                    <td class="py-1">Total Cost</td>
                                    <td class="py-1 text-right">${{ coin.total_cost|floatformat:2|intcomma }} CAD</td>
                                </tr>
                                <tr>
                                    <td class="py-1">Balance</td>
                                    <td class="py-1 text-right">{{ coin.balance|floatformat:5|intcomma }} {{ coin.coin_ticker.upper }}</td>
                                </tr>
                            </table>
                            <a href="{% url 'AppCoinStash:detail' coin.coin_ticker %}" class="card-link">Transactions</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="text-center" style="margin-top: 50px;">
            <h4 style="margin-bottom: 50px;">Add coins to your portfolio using the search bar.</h4>
            <img alt='logo.jpg' style="margin-bottom: 50px;" src="{% static 'AppCoinStash/images/logo_512px.png' %}">
        </div>
    {% endif %}
    <script>
        let search_terms = [];
        let coin_ids = [];

        function clearSearch() {
            $('#result').attr('hidden', '');
        }

        function fill_search_input(input) {
            $('#new_coin').val(coin_ids[input.value]);
            $('#submit_coin').removeAttr('disabled')
        }

        function searchCoinList(input) {
            input = input.trim()
            $.ajax({
                method: "GET",
                url: "http://127.0.0.1:8000/coinsearch/?search_string=" + input
            })
                .done(function(coin_list) {
                    search_terms = [];
                    coin_ids = [];
                    for (let i=0; i<coin_list.length; i++) {
                        let coin = coin_list[i];
                        search_terms.push(coin['coin_name'] + ' ($' + coin['coin_symbol'].toUpperCase() + ')');
                        coin_ids.push(coin['coin_id']);
                    }
                    showResults(input);
                });
        }

        function showResults(val) {
            let result_div = $('#result')
            if (val === '' || search_terms.length < 1) {
                result_div.attr('hidden', '');
                return
            }

            let res = document.getElementById("result");
            res.innerHTML = '';
            let list = '';
            for (let i=0; i<search_terms.length; i++) {
                list += '<li onmousedown="fill_search_input(this)" value=' + i + '>';
                list += search_terms[i];
                list += '</li>';
            }
            result_div.removeAttr('hidden')
            res.innerHTML = '<ol>' + list + '</ol>';
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
    <script src="{% static 'AppCoinStash/homechart.js' %}"></script>
{% endblock %}

AppCoinStash/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_specific_style %}
    <style>
        .row {
            height: 65vh;
            align-items: center;
        }
        h2 {
            font-size: 60px;
        }
        #row1 {
            background-image: url({% static 'AppCoinStash/images/bg5.png' %});
            background-size: cover;
        }
        #row2_container {
            background: whitesmoke;
        }
        #row3_container {
            background-image: url({% static 'AppCoinStash/images/bg7.jpg' %});
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }
        .content-center {
            background: #eee;
            border-radius: 5px;
            padding: 2em;
            text-align: center;
            max-width: 600px;
            border-bottom: 5px solid #4f4f4f;
        }
        .demo_vid {
            border-radius: 10px;

        }
        #chart_vid {
            box-shadow: 10px 10px 5px grey;
        }
        #trans_vid {
            box-shadow: -10px 10px 5px midnightblue;
        }
        #get_started_btn {
            border-radius: 15px;
            padding: 0.5em;
            color: white;
            background-color: #4f4f4f;
            border: none;
        }
        #get_started_btn:hover {
            background-color: #292929;
        }
        .footer {
            background-color: #292929;
            color: whitesmoke;
            text-align: center;
            padding: 1em;
        }
    </style>
{% endblock %}

{% block title %}CoinStash{% endblock %}

{% block content-fluid %}
    <div id="row1" class="row m-0 p-0 justify-content-center">
        <div class="content-center">
            <h2>Simple. Easy. Free.</h2>
            <p>Manage your cryptocurrency investments with CoinStash.<br>
                Thousands of coins supported by the CoinGecko API.
                Make informed investments without getting lost in the numbers.
            </p>
            <a class="btn" id="get_started_btn" href="{% url 'AppCoinStash:register' %}">Get started</a>
        </div>
    </div>
    <div id="row2_container" class="container-fluid">
        <div class="container">
            <div class="row m-0 p-0">
                <div class="col m-0 p-0">
                    <h2 style="text-decoration: underline">At a glance</h2>
                    <p>
                        CoinStash provides an overview of your investments.
                        Quickly assess your portfolio using metrics such as average cost,
                        total cost, and gain/loss percentage.
                    </p>
                </div>
                <div class="col m-0 p-0 text-right">
                    <video id="chart_vid" class="demo_vid" height="400" autoplay="autoplay" loop muted>
                        <source src="{% static 'AppCoinStash/videos/chartdemo.mp4' %}" type="video/mp4" />
                    </video>
                </div>
            </div>
        </div>
    </div>
    <div id="row3_container" class="container-fluid">
        <div class="container">
            <div class="row my-0 py-0">
                <div class="col text-center">
                    <video id="trans_vid" class="demo_vid" height="400" autoplay="autoplay" loop muted>
                        <source src="{% static 'AppCoinStash/videos/transdemo.mp4' %}" type="video/mp4" />
                    </video>
                </div>
                <div class="col text-right" style="color: whitesmoke;">
                    <h2 style="text-decoration: underline;">Manage</h2>
                    <p>
                        CoinStash gives you complete control over your transaction
                        history. Add or remove transactions as you see fit.
                    </p>
                    <p>
                        (Coming soon) Import your trades by uploading CSV files.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <p>
            CoinStash is a project by <a target="_blank" href="https://github.com/dfloren">dfloren</a>. Made with Django &#128150;
        </p>
            <a target="_blank" href="https://github.com/dfloren" style="color: white;"><i class="fa-brands fa-github fa-2xl"></i></a>
    </div>
    <script>
        const parallax = document.getElementById("row1")

        window.addEventListener("scroll", function() {
            parallax.style.backgroundPositionY = window.scrollY * 0.4 + "px";
        })
    </script>
{% endblock %}